id-worker:
  config:
    datacenterId: 1
    workerId: 1

limiter:
  config:
    concurrent-num: 1

stock:
  config:
    market:
      inner:
        - s_sh000001 # 上证ID
        - s_sz399001 #  深证ID
      outer:
        - int_dji # 道琼斯
        - int_nasdaq # 纳斯达克
        - int_hangseng # 恒生
        - int_nikkei # 日经指数
        - b_TWSE # 台湾加权
        - b_FSSTI # 新加坡
      threshold:
        increase: 0.10  # 默认涨幅阈值（10%）
        decrease: -0.10 # 默认跌幅阈值（-10%）

spring:
  devtools:
    restart:
      enabled: false
